import '../../l10n/app_strings.dart';

void registerIdentityMigrationNoticeStrings() {
  AppStrings.registerStrings(_bundle);
}

const _bundle = <String, Map<String, String>>{
  'en': {
    'legacyIdentityNoticeTitle': 'Important identity update',
    'legacyIdentityNoticeBody': 'Your current identity was created with an early format used in the first public versions of the app. To ensure stable recovery using your recovery phrase going forward, please create a new identity.',
    'legacyIdentityNoticeRemindLater': 'Remind me later',
    'legacyIdentityNoticeUnderstand': 'I understand',
  },
  'it': {
    'legacyIdentityNoticeTitle': 'Aggiornamento importante dell\'identità',
    'legacyIdentityNoticeBody': 'La tua identità attuale è stata creata con un formato iniziale usato nelle prime versioni pubbliche dell\'app. Per garantire un recupero stabile con la tua frase di recupero in futuro, crea una nuova identità.',
    'legacyIdentityNoticeRemindLater': 'Ricordamelo più tardi',
    'legacyIdentityNoticeUnderstand': 'Ho capito',
  },
  'es': {
    'legacyIdentityNoticeTitle': 'Actualización importante de identidad',
    'legacyIdentityNoticeBody': 'Tu identidad actual fue creada con un formato temprano usado en las primeras versiones públicas de la app. Para garantizar una recuperación estable con tu frase de recuperación en el futuro, crea una nueva identidad.',
    'legacyIdentityNoticeRemindLater': 'Recuérdamelo más tarde',
    'legacyIdentityNoticeUnderstand': 'Entiendo',
  },
  'pt': {
    'legacyIdentityNoticeTitle': 'Atualização importante de identidade',
    'legacyIdentityNoticeBody': 'Sua identidade atual foi criada com um formato inicial usado nas primeiras versões públicas do app. Para garantir uma recuperação estável com sua frase de recuperação daqui para frente, crie uma nova identidade.',
    'legacyIdentityNoticeRemindLater': 'Lembrar mais tarde',
    'legacyIdentityNoticeUnderstand': 'Entendi',
  },
  'pt_PT': {
    'legacyIdentityNoticeTitle': 'Atualização importante da identidade',
    'legacyIdentityNoticeBody': 'A sua identidade atual foi criada com um formato inicial usado nas primeiras versões públicas da aplicação. Para garantir uma recuperação estável com a sua frase de recuperação no futuro, crie uma nova identidade.',
    'legacyIdentityNoticeRemindLater': 'Lembrar mais tarde',
    'legacyIdentityNoticeUnderstand': 'Compreendo',
  },
  'ru': {
    'legacyIdentityNoticeTitle': 'Важное обновление идентичности',
    'legacyIdentityNoticeBody': 'Ваша текущая идентичность была создана в раннем формате, использовавшемся в первых публичных версиях приложения. Чтобы в дальнейшем обеспечить стабильное восстановление по фразе восстановления, создайте новую идентичность.',
    'legacyIdentityNoticeRemindLater': 'Напомнить позже',
    'legacyIdentityNoticeUnderstand': 'Понятно',
  },
  'id': {
    'legacyIdentityNoticeTitle': 'Pembaruan identitas penting',
    'legacyIdentityNoticeBody': 'Identitas Anda saat ini dibuat dengan format awal yang digunakan pada versi publik pertama aplikasi. Untuk memastikan pemulihan yang stabil dengan frasa pemulihan Anda ke depannya, buat identitas baru.',
    'legacyIdentityNoticeRemindLater': 'Ingatkan saya nanti',
    'legacyIdentityNoticeUnderstand': 'Saya mengerti',
  },
  'ar': {
    'legacyIdentityNoticeTitle': 'تحديث مهم للهوية',
    'legacyIdentityNoticeBody': 'تم إنشاء هويتك الحالية بصيغة مبكرة استُخدمت في أول الإصدارات العامة من التطبيق. لضمان استعادة مستقرة باستخدام عبارة الاسترداد الخاصة بك مستقبلاً، يرجى إنشاء هوية جديدة.',
    'legacyIdentityNoticeRemindLater': 'ذكّرني لاحقًا',
    'legacyIdentityNoticeUnderstand': 'فهمت',
  },
  'fr': {
    'legacyIdentityNoticeTitle': 'Mise à jour importante de l\'identité',
    'legacyIdentityNoticeBody': 'Votre identité actuelle a été créée avec un ancien format utilisé dans les premières versions publiques de l\'application. Pour garantir une récupération stable avec votre phrase de récupération à l\'avenir, veuillez créer une nouvelle identité.',
    'legacyIdentityNoticeRemindLater': 'Me le rappeler plus tard',
    'legacyIdentityNoticeUnderstand': 'J\'ai compris',
  },
  'de': {
    'legacyIdentityNoticeTitle': 'Wichtiges Identitätsupdate',
    'legacyIdentityNoticeBody': 'Ihre aktuelle Identität wurde mit einem frühen Format erstellt, das in den ersten öffentlichen Versionen der App verwendet wurde. Damit die Wiederherstellung mit Ihrer Wiederherstellungsphrase künftig zuverlässig funktioniert, erstellen Sie bitte eine neue Identität.',
    'legacyIdentityNoticeRemindLater': 'Später erinnern',
    'legacyIdentityNoticeUnderstand': 'Ich verstehe',
  },
  'hi': {
    'legacyIdentityNoticeTitle': 'महत्वपूर्ण पहचान अपडेट',
    'legacyIdentityNoticeBody': 'आपकी वर्तमान पहचान ऐप के शुरुआती सार्वजनिक संस्करणों में इस्तेमाल किए गए पुराने फ़ॉर्मेट में बनाई गई थी। आगे आपकी रिकवरी फ़्रेज़ से स्थिर रिकवरी सुनिश्चित करने के लिए कृपया नई पहचान बनाएँ।',
    'legacyIdentityNoticeRemindLater': 'मुझे बाद में याद दिलाएँ',
    'legacyIdentityNoticeUnderstand': 'मैं समझ गया',
  },
  'nl': {
    'legacyIdentityNoticeTitle': 'Belangrijke identiteitsupdate',
    'legacyIdentityNoticeBody': 'Je huidige identiteit is gemaakt met een vroeg formaat dat in de eerste openbare versies van de app werd gebruikt. Maak een nieuwe identiteit aan om in de toekomst een stabiel herstel met je herstelzin te garanderen.',
    'legacyIdentityNoticeRemindLater': 'Herinner me later',
    'legacyIdentityNoticeUnderstand': 'Ik begrijp het',
  },
  'fa': {
    'legacyIdentityNoticeTitle': 'به‌روزرسانی مهم هویت',
    'legacyIdentityNoticeBody': 'هویت فعلی شما با یک قالب اولیه ساخته شده که در نخستین نسخه‌های عمومی برنامه استفاده می‌شد. برای اینکه بازیابی با عبارت بازیابی شما در آینده پایدار باشد، لطفاً یک هویت جدید ایجاد کنید.',
    'legacyIdentityNoticeRemindLater': 'بعداً یادآوری کن',
    'legacyIdentityNoticeUnderstand': 'متوجه شدم',
  },
  'ro': {
    'legacyIdentityNoticeTitle': 'Actualizare importantă a identității',
    'legacyIdentityNoticeBody': 'Identitatea ta actuală a fost creată într-un format timpuriu folosit în primele versiuni publice ale aplicației. Pentru a asigura o recuperare stabilă folosind fraza ta de recuperare pe viitor, creează o identitate nouă.',
    'legacyIdentityNoticeRemindLater': 'Amintește-mi mai târziu',
    'legacyIdentityNoticeUnderstand': 'Am înțeles',
  },
  'pl': {
    'legacyIdentityNoticeTitle': 'Ważna aktualizacja tożsamości',
    'legacyIdentityNoticeBody': 'Twoja obecna tożsamość została utworzona w starszym formacie używanym we wczesnych publicznych wersjach aplikacji. Aby w przyszłości zapewnić stabilne odzyskiwanie przy użyciu frazy odzyskiwania, utwórz nową tożsamość.',
    'legacyIdentityNoticeRemindLater': 'Przypomnij mi później',
    'legacyIdentityNoticeUnderstand': 'Rozumiem',
  },
  'zh': {
    'legacyIdentityNoticeTitle': '重要身份更新',
    'legacyIdentityNoticeBody': '你当前的身份是使用应用最早公开版本中的早期格式创建的。为了确保今后能够通过恢复短语稳定恢复，请创建一个新的身份。',
    'legacyIdentityNoticeRemindLater': '稍后提醒我',
    'legacyIdentityNoticeUnderstand': '我明白了',
  },
  'tr': {
    'legacyIdentityNoticeTitle': 'Önemli kimlik güncellemesi',
    'legacyIdentityNoticeBody': 'Mevcut kimliğiniz, uygulamanın ilk genel sürümlerinde kullanılan erken bir biçimle oluşturuldu. Kurtarma ifadenizle gelecekte kararlı bir kurtarma sağlamak için lütfen yeni bir kimlik oluşturun.',
    'legacyIdentityNoticeRemindLater': 'Daha sonra hatırlat',
    'legacyIdentityNoticeUnderstand': 'Anladım',
  },
  'ja': {
    'legacyIdentityNoticeTitle': '重要なID更新',
    'legacyIdentityNoticeBody': '現在のIDは、アプリの初期の公開版で使われていた初期形式で作成されています。今後も復旧フレーズで安定して復元できるように、新しいIDを作成してください。',
    'legacyIdentityNoticeRemindLater': '後で知らせる',
    'legacyIdentityNoticeUnderstand': '理解しました',
  },
  'ko': {
    'legacyIdentityNoticeTitle': '중요한 신원 업데이트',
    'legacyIdentityNoticeBody': '현재 신원은 앱의 초기 공개 버전에서 사용된 초기 형식으로 만들어졌습니다. 앞으로 복구 문구로 안정적으로 복구할 수 있도록 새 신원을 만들어 주세요.',
    'legacyIdentityNoticeRemindLater': '나중에 다시 알리기',
    'legacyIdentityNoticeUnderstand': '이해했습니다',
  },
  'vi': {
    'legacyIdentityNoticeTitle': 'Cập nhật danh tính quan trọng',
    'legacyIdentityNoticeBody': 'Danh tính hiện tại của bạn được tạo bằng định dạng ban đầu được dùng trong các phiên bản công khai đầu tiên của ứng dụng. Để đảm bảo khôi phục ổn định bằng cụm từ khôi phục về sau, vui lòng tạo danh tính mới.',
    'legacyIdentityNoticeRemindLater': 'Nhắc tôi sau',
    'legacyIdentityNoticeUnderstand': 'Tôi hiểu',
  },
  'th': {
    'legacyIdentityNoticeTitle': 'การอัปเดตตัวตนที่สำคัญ',
    'legacyIdentityNoticeBody': 'ตัวตนปัจจุบันของคุณถูกสร้างด้วยรูปแบบเริ่มต้นที่ใช้ในแอปเวอร์ชันสาธารณะช่วงแรก เพื่อให้การกู้คืนด้วยวลีการกู้คืนของคุณมีความเสถียรในอนาคต โปรดสร้างตัวตนใหม่',
    'legacyIdentityNoticeRemindLater': 'เตือนฉันภายหลัง',
    'legacyIdentityNoticeUnderstand': 'ฉันเข้าใจ',
  },
  'el': {
    'legacyIdentityNoticeTitle': 'Σημαντική ενημέρωση ταυτότητας',
    'legacyIdentityNoticeBody': 'Η τρέχουσα ταυτότητά σας δημιουργήθηκε με μια πρώιμη μορφή που χρησιμοποιήθηκε στις πρώτες δημόσιες εκδόσεις της εφαρμογής. Για να διασφαλιστεί σταθερή ανάκτηση με τη φράση ανάκτησής σας στο μέλλον, δημιουργήστε μια νέα ταυτότητα.',
    'legacyIdentityNoticeRemindLater': 'Υπενθύμιση αργότερα',
    'legacyIdentityNoticeUnderstand': 'Κατάλαβα',
  },
  'bn': {
    'legacyIdentityNoticeTitle': 'গুরুত্বপূর্ণ পরিচয় আপডেট',
    'legacyIdentityNoticeBody': 'আপনার বর্তমান পরিচয় অ্যাপের প্রথম পাবলিক সংস্করণগুলিতে ব্যবহৃত একটি পুরোনো ফরম্যাটে তৈরি হয়েছে। ভবিষ্যতে আপনার রিকভারি ফ্রেজ দিয়ে স্থিতিশীল পুনরুদ্ধার নিশ্চিত করতে অনুগ্রহ করে একটি নতুন পরিচয় তৈরি করুন।',
    'legacyIdentityNoticeRemindLater': 'পরে মনে করিয়ে দিন',
    'legacyIdentityNoticeUnderstand': 'আমি বুঝেছি',
  },
  'mr': {
    'legacyIdentityNoticeTitle': 'महत्त्वाचे ओळख अद्यतन',
    'legacyIdentityNoticeBody': 'तुमची सध्याची ओळख अॅपच्या सुरुवातीच्या सार्वजनिक आवृत्त्यांमध्ये वापरल्या गेलेल्या जुन्या स्वरूपात तयार झाली आहे. पुढे तुमच्या रिकव्हरी वाक्यांशाद्वारे स्थिर पुनर्प्राप्ती सुनिश्चित करण्यासाठी कृपया नवी ओळख तयार करा.',
    'legacyIdentityNoticeRemindLater': 'मला नंतर आठवण करून द्या',
    'legacyIdentityNoticeUnderstand': 'मला समजले',
  },
  'ur': {
    'legacyIdentityNoticeTitle': 'اہم شناختی اپ ڈیٹ',
    'legacyIdentityNoticeBody': 'آپ کی موجودہ شناخت ایک ابتدائی فارمیٹ میں بنائی گئی تھی جو ایپ کے پہلے عوامی ورژنز میں استعمال ہوتا تھا۔ آئندہ اپنی ریکوری فریز کے ذریعے مستحکم بحالی یقینی بنانے کے لیے براہ کرم نئی شناخت بنائیں۔',
    'legacyIdentityNoticeRemindLater': 'مجھے بعد میں یاد دلائیں',
    'legacyIdentityNoticeUnderstand': 'میں سمجھ گیا',
  },
  'fi': {
    'legacyIdentityNoticeTitle': 'Tärkeä identiteettipäivitys',
    'legacyIdentityNoticeBody': 'Nykyinen identiteettisi luotiin varhaisella muodolla, jota käytettiin sovelluksen ensimmäisissä julkisissa versioissa. Luo uusi identiteetti, jotta palautus palautuslauseella toimii jatkossa vakaasti.',
    'legacyIdentityNoticeRemindLater': 'Muistuta myöhemmin',
    'legacyIdentityNoticeUnderstand': 'Ymmärrän',
  },
  'no': {
    'legacyIdentityNoticeTitle': 'Viktig identitetsoppdatering',
    'legacyIdentityNoticeBody': 'Den nåværende identiteten din ble opprettet med et tidlig format som ble brukt i de første offentlige versjonene av appen. For å sikre stabil gjenoppretting med gjenopprettingsfrasen din fremover, opprett en ny identitet.',
    'legacyIdentityNoticeRemindLater': 'Minn meg på det senere',
    'legacyIdentityNoticeUnderstand': 'Jeg forstår',
  },
  'sv': {
    'legacyIdentityNoticeTitle': 'Viktig identitetsuppdatering',
    'legacyIdentityNoticeBody': 'Din nuvarande identitet skapades med ett tidigt format som användes i appens första offentliga versioner. Skapa en ny identitet för att säkerställa stabil återställning med din återställningsfras framöver.',
    'legacyIdentityNoticeRemindLater': 'Påminn mig senare',
    'legacyIdentityNoticeUnderstand': 'Jag förstår',
  },
  'uk': {
    'legacyIdentityNoticeTitle': 'Важливе оновлення ідентичності',
    'legacyIdentityNoticeBody': 'Вашу поточну ідентичність було створено у ранньому форматі, що використовувався в перших публічних версіях застосунку. Щоб надалі забезпечити стабільне відновлення за допомогою фрази відновлення, створіть нову ідентичність.',
    'legacyIdentityNoticeRemindLater': 'Нагадати пізніше',
    'legacyIdentityNoticeUnderstand': 'Зрозуміло',
  },
  'sq': {
    'legacyIdentityNoticeTitle': 'Përditësim i rëndësishëm i identitetit',
    'legacyIdentityNoticeBody': 'Identiteti juaj aktual u krijua me një format të hershëm të përdorur në versionet e para publike të aplikacionit. Për të siguruar rikuperim të qëndrueshëm me frazën tuaj të rikuperimit në vazhdim, krijoni një identitet të ri.',
    'legacyIdentityNoticeRemindLater': 'Më kujto më vonë',
    'legacyIdentityNoticeUnderstand': 'E kuptoj',
  },
  'ca': {
    'legacyIdentityNoticeTitle': 'Actualització important de la identitat',
    'legacyIdentityNoticeBody': 'La teva identitat actual es va crear amb un format inicial utilitzat a les primeres versions públiques de l\'aplicació. Per garantir una recuperació estable amb la teva frase de recuperació d\'ara endavant, crea una nova identitat.',
    'legacyIdentityNoticeRemindLater': 'Recorda-m\'ho més tard',
    'legacyIdentityNoticeUnderstand': 'Ho entenc',
  },
  'sw': {
    'legacyIdentityNoticeTitle': 'Sasisho muhimu la utambulisho',
    'legacyIdentityNoticeBody': 'Utambulisho wako wa sasa uliundwa kwa muundo wa awali uliotumika katika matoleo ya kwanza ya umma ya programu. Ili kuhakikisha urejeshaji thabiti kwa kutumia kauli yako ya urejeshaji kuanzia sasa, tafadhali tengeneza utambulisho mpya.',
    'legacyIdentityNoticeRemindLater': 'Nikumbushe baadaye',
    'legacyIdentityNoticeUnderstand': 'Nimeelewa',
  },
  'ha': {
    'legacyIdentityNoticeTitle': 'Muhimmin sabuntawar shaidar ainihi',
    'legacyIdentityNoticeBody': 'An ƙirƙiri shaidar ka ta yanzu da tsohon tsari da aka yi amfani da shi a farkon sigogin jama\'a na manhajar. Don tabbatar da daidaitacciyar dawo da bayanai ta amfani da kalmar dawo da kai a gaba, ƙirƙiri sabuwar shaida.',
    'legacyIdentityNoticeRemindLater': 'Tunatar da ni daga baya',
    'legacyIdentityNoticeUnderstand': 'Na fahimta',
  },
  'tl': {
    'legacyIdentityNoticeTitle': 'Mahalagang update sa pagkakakilanlan',
    'legacyIdentityNoticeBody': 'Ang kasalukuyan mong pagkakakilanlan ay ginawa gamit ang maagang format na ginamit sa mga unang pampublikong bersyon ng app. Para matiyak ang matatag na pagbawi gamit ang iyong recovery phrase sa hinaharap, gumawa ng bagong pagkakakilanlan.',
    'legacyIdentityNoticeRemindLater': 'Ipaalala sa akin mamaya',
    'legacyIdentityNoticeUnderstand': 'Naiintindihan ko',
  },
  'ms': {
    'legacyIdentityNoticeTitle': 'Kemas kini identiti penting',
    'legacyIdentityNoticeBody': 'Identiti semasa anda dicipta menggunakan format awal yang digunakan dalam versi awam terawal aplikasi. Untuk memastikan pemulihan yang stabil menggunakan frasa pemulihan anda pada masa hadapan, sila cipta identiti baharu.',
    'legacyIdentityNoticeRemindLater': 'Ingatkan saya kemudian',
    'legacyIdentityNoticeUnderstand': 'Saya faham',
  },
  'ta': {
    'legacyIdentityNoticeTitle': 'முக்கிய அடையாள புதுப்பிப்பு',
    'legacyIdentityNoticeBody': 'உங்கள் தற்போதைய அடையாளம் பயன்பாட்டின் ஆரம்ப பொதுப் பதிப்புகளில் பயன்படுத்தப்பட்ட ஆரம்ப வடிவத்தில் உருவாக்கப்பட்டது. இனிமேல் உங்கள் மீட்பு சொற்றொடரைப் பயன்படுத்தி நிலையான மீட்பை உறுதிசெய்ய புதிய அடையாளத்தை உருவாக்கவும்.',
    'legacyIdentityNoticeRemindLater': 'பிறகு நினைவூட்டவும்',
    'legacyIdentityNoticeUnderstand': 'எனக்கு புரிந்தது',
  },
  'te': {
    'legacyIdentityNoticeTitle': 'ముఖ్యమైన గుర్తింపు నవీకరణ',
    'legacyIdentityNoticeBody': 'మీ ప్రస్తుత గుర్తింపు యాప్ తొలి ప్రజా సంచికల్లో ఉపయోగించిన ప్రారంభ ఫార్మాట్‌తో సృష్టించబడింది. ఇకముందు మీ రికవరీ ఫ్రేజ్‌తో స్థిరమైన పునరుద్ధరణను నిర్ధారించడానికి దయచేసి కొత్త గుర్తింపును సృష్టించండి.',
    'legacyIdentityNoticeRemindLater': 'నన్ను తర్వాత గుర్తుచేయండి',
    'legacyIdentityNoticeUnderstand': 'నాకు అర్థమైంది',
  },
  'gu': {
    'legacyIdentityNoticeTitle': 'મહત્વપૂર્ણ ઓળખ અપડેટ',
    'legacyIdentityNoticeBody': 'તમારી હાલની ઓળખ એપ્લિકેશનની શરૂઆતની જાહેર આવૃત્તિઓમાં ઉપયોગમાં લેવાયેલા પ્રારંભિક ફોર્મેટમાં બનાવવામાં આવી હતી. આગળ તમારી રિકવરી ફ્રેઝથી સ્થિર પુનઃપ્રાપ્તિ સુનિશ્ચિત કરવા કૃપા કરીને નવી ઓળખ બનાવો.',
    'legacyIdentityNoticeRemindLater': 'મને પછી યાદ કરાવજો',
    'legacyIdentityNoticeUnderstand': 'હું સમજ્યો',
  },
  'kn': {
    'legacyIdentityNoticeTitle': 'ಪ್ರಮುಖ ಗುರುತು ನವೀಕರಣ',
    'legacyIdentityNoticeBody': 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಗುರುತು ಆಪ್‌ನ ಮೊದಲ ಸಾರ್ವಜನಿಕ ಆವೃತ್ತಿಗಳಲ್ಲಿ ಬಳಸಲಾದ ಆರಂಭಿಕ ಸ್ವರೂಪದಲ್ಲಿ ರಚಿಸಲಾಗಿದೆ. ಮುಂದಿನ ದಿನಗಳಲ್ಲಿ ನಿಮ್ಮ ಮರುಪಡೆಯುವ ವಾಕ್ಯದ ಮೂಲಕ ಸ್ಥಿರ ಮರುಪಡೆಯುವಿಕೆ ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ದಯವಿಟ್ಟು ಹೊಸ ಗುರುತನ್ನು ರಚಿಸಿ.',
    'legacyIdentityNoticeRemindLater': 'ನನಗೆ ನಂತರ ನೆನಪಿಸಿ',
    'legacyIdentityNoticeUnderstand': 'ನನಗೆ ಅರ್ಥವಾಗಿದೆ',
  },
  'pa': {
    'legacyIdentityNoticeTitle': 'ਮਹੱਤਵਪੂਰਣ ਪਹਿਚਾਣ ਅੱਪਡੇਟ',
    'legacyIdentityNoticeBody': 'ਤੁਹਾਡੀ ਮੌਜੂਦਾ ਪਹਿਚਾਣ ਐਪ ਦੇ ਪਹਿਲੇ ਜਨਤਕ ਸੰਸਕਰਣਾਂ ਵਿੱਚ ਵਰਤੇ ਗਏ ਪੁਰਾਣੇ ਫਾਰਮੈਟ ਨਾਲ ਬਣਾਈ ਗਈ ਸੀ। ਅੱਗੇ ਤੁਹਾਡੀ ਰਿਕਵਰੀ ਫਰੇਜ਼ ਨਾਲ ਸਥਿਰ ਮੁੜ ਪ੍ਰਾਪਤੀ ਯਕੀਨੀ ਬਣਾਉਣ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਨਵੀਂ ਪਹਿਚਾਣ ਬਣਾਓ।',
    'legacyIdentityNoticeRemindLater': 'ਮੈਨੂੰ ਬਾਅਦ ਵਿੱਚ ਯਾਦ ਦਿਵਾਓ',
    'legacyIdentityNoticeUnderstand': 'ਮੈਂ ਸਮਝ ਗਿਆ',
  },
  'am': {
    'legacyIdentityNoticeTitle': 'አስፈላጊ የመለያ ማሻሻያ',
    'legacyIdentityNoticeBody': 'አሁን ያለዎት መለያ በመተግበሪያው የመጀመሪያ የህዝብ ስሪቶች ላይ የተጠቀሙበት ቀደም ያለ ፎርማት ነው። ወደፊት በመመለሻ ሐረግዎ የተረጋጋ መመለስ እንዲረጋገጥ አዲስ መለያ ይፍጠሩ።',
    'legacyIdentityNoticeRemindLater': 'በኋላ አስታውሰኝ',
    'legacyIdentityNoticeUnderstand': 'ተረድቻለሁ',
  },
  'yo': {
    'legacyIdentityNoticeTitle': 'Imudojuiwọn idanimọ pataki',
    'legacyIdentityNoticeBody': 'A ṣẹda idanimọ lọwọlọwọ rẹ pẹlu ọna kika atijọ ti a lo ninu awọn ẹya gbangba akọkọ ti ohun elo naa. Lati jẹrisi imupadabọ iduroṣinṣin pẹlu gbolohun imupadabọ rẹ lọ́jọ iwájú, jọwọ ṣẹda idanimọ tuntun.',
    'legacyIdentityNoticeRemindLater': 'Ranti mi nigbamii',
    'legacyIdentityNoticeUnderstand': 'Mo ye',
  },
};
